bump_version: null
lint:
  files_exist:
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - assets/multiqc_config.yml
  - nextflow_schema.json
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - assets/multiqc_config.yml
  - nextflow_schema.json
  - CODE_OF_CONDUCT.md
  - assets/nf-core-bfflow_logo_light.png
  - docs/images/nf-core-bfflow_logo_light.png
  - docs/images/nf-core-bfflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - .github/CONTRIBUTING.md
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - .prettierignore
  - .prettierignore
  - .github/CONTRIBUTING.md
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - .prettierignore
  - .prettierignore
  - CODE_OF_CONDUCT.md
  - assets/nf-core-bfflow_logo_light.png
  - docs/images/nf-core-bfflow_logo_light.png
  - docs/images/nf-core-bfflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config: false
  nextflow_config: false
  schema_description: false
  schema_lint: false
  schema_params: false
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: bugraoezdemir
  description: Converts image to OME-TIFF format.
  force: true
  is_nfcore: false
  name: bfflow
  org: Euro-BioImaging
  outdir: .
  skip_features:
  - igenomes
  - codespaces
  - multiqc
  - fastqc
  - nf_schema
  - adaptivecard
  - slackreport
  - seqera_platform
  version: 0.0.0dev
update: null
