# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bfconvert"
description: Contrast-limited adjusted histogram equalization (CLAHE) on single-channel
  tif images.
keywords:
  - image
  - OME-TIFF
  - file format
  - conversion
tools:
  - "bfconvert":
      description: "Data conversion to OME-TIFF"
      homepage: https://github.com/SchapiroLabor/molkart-local/tree/main
      documentation: https://github.com/SchapiroLabor/molkart-local/tree/main
      tool_dev_url: https://github.com/SchapiroLabor/molkart-local/blob/main/scripts/molkart_clahe.py
      licence: ["MIT"]
      identifier: ""

input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1']`
    - image:
        type: file
        description: Image file to be converted.
        pattern: "*"
output:
  #Only when we have meta
  - img_clahe:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1']`
      - "*ome.tiff":
          type: file
          description: OME-TIFF file.
          pattern: "*.{tif,tiff}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@bugraoezdemir"
maintainers:
  - "@bugraoezdemir"
